version: '3'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  server:
    build: server
    environment:
      - PORT=8080
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=93a04706d8a1d56604f7050a56d8db4bfeccedcf33dda015556e165693c97846
      - MONGO_URI=mongodb+srv://femil:dgFEJP2nuwOquaNn@cluster0.sztp9fu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - '8080:8080'
